### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[16, 320, 3, 320] to have 3 channels, but got 320 channels instead

### ISSUE THREAD

**Issue by TikhonovAleksey-AI** [USC-ACTLab/MAPFAST#2]
Hello!
Can this implementation be run on a new version of touchvision ?
Trying to run on a new version results in an error:

`C:\Users\user\Documents\GitHub\MAPFAST\venv\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\MAPFAST\main.py", line 85, in <module>
    train(device, config)
  File "C:\Users\user\Documents\GitHub\MAPFAST\main.py", line 33, in train
    net = mapfast.train_model(train_list, valid_list, model_loc, model_name, batch_size, epochs, log_interval, cl_units, fin_pred_units, pair_units)
  File "C:\Users\user\Documents\GitHub\MAPFAST\MAPFAST.py", line 248, in train_model
    outs = net(X_to)
  File "C:\Users\user\Documents\GitHub\MAPFAST\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Documents\GitHub\MAPFAST\utils.py", line 122, in forward
    cov1 = self.conv1(x1)
  File "C:\Users\user\Documents\GitHub\MAPFAST\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Documents\GitHub\MAPFAST\utils.py", line 44, in forward
    return self.net(x)
  File "C:\Users\user\Documents\GitHub\MAPFAST\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Documents\GitHub\MAPFAST\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\user\Documents\GitHub\MAPFAST\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[16, 320, 3, 320] to have 3 channels, but got 320 channels instead`

Can you tell me how to change the code so that the implementation can be started.

**Comment by TikhonovAleksey-AI** [comment]
commented out the line ~173 in the MAP FAST file:
`#new_image = np.transpose(new_image, (2, 0, 1))`
